# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField()),
                ('vegetarian', models.BooleanField()),
                ('other_dietary_restrictions', models.TextField(blank=True)),
                ('attending_dates', models.CommaSeparatedIntegerField(blank=True, choices=[(1, 'Saturday evening reception'), (2, 'Sunday morning wedding ceremony and brunch')], max_length=4)),
                ('need_carpool_info', models.BooleanField()),
                ('need_hotel_info', models.BooleanField()),
                ('plus_one', models.BooleanField()),
                ('plus_one_name', models.CharField(default=None, max_length=200, unique=True)),
                ('song_requests', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edited_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
