# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_auto_20151217_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='vegetarian',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='vegetarian_diet',
            field=models.BooleanField(default=''),
            preserve_default=False,
        ),
    ]
