# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_auto_20151224_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='need_carpool_info',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='need_hotel_info',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='plus_one',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='vegetarian_diet',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='need_carpool',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='need_hotel',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='plus_one_guest',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='vegetarian',
            field=models.NullBooleanField(),
        ),
    ]
