# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_auto_20151224_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='plus_one_name',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='plus_one_n',
            field=models.CharField(blank=True, default=None, max_length=200, unique=True),
        ),
    ]
