# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0007_auto_20151224_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='number_attendees',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
