# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0008_rsvp_number_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='formal_prefix',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
