# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0011_auto_20160403_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='affiliation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='gift',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='expected_attendees',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
    ]
