# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0012_auto_20160403_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='sent_emails',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='plus_one',
            field=models.BooleanField(default=False),
        ),
    ]
