# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0013_auto_20160411_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='sent_emails',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
