# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0014_auto_20160411_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='other_dietary_restrictions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
