# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0015_auto_20160411_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
