# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0016_rsvp_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='song_requests',
            field=models.TextField(blank=True, default=''),
        ),
    ]
