# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0017_auto_20160426_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='wine_tasting',
            field=models.NullBooleanField(),
        ),
    ]
