# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0019_auto_20160621_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='gift_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='gift_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='gift_type',
            field=models.CommaSeparatedIntegerField(blank=True, choices=[(0, 'Airfare'), (1, 'Day 1 in Bhutan'), (2, 'Day 2 in Bhutan'), (3, 'Day 3 in Bhutan'), (4, 'Day 4 in Bhutan'), (5, 'Day 5 in Bhutan'), (6, 'Day 6 in Bhutan'), (7, 'Day 7 in Bhutan'), (8, 'Day 8 in Bhutan'), (-1, 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='thank_you_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='gift',
            field=models.NullBooleanField(default=False),
        ),
    ]
