# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0020_auto_20160902_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
