# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0021_rsvp_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='thank_you_message',
        ),
    ]
