# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0022_remove_rsvp_thank_you_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='gift_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
